### ISSUE TITLE
Soldier null pointer exception

### ISSUE THREAD

**Issue by Lukx19** [hrnr/battlecode-2017-blueteam#17]
Stack trace: 
java.lang.NullPointerException: Argument has an invalid null value
at battlecode.world.RobotControllerImpl.assertNotNull(RobotControllerImpl.java:63)
at battlecode.world.RobotControllerImpl.canMove(RobotControllerImpl.java:530)
at battlecode.world.RobotControllerImpl.canMove(RobotControllerImpl.java:525)
at blueteam.Soldier.step(Soldier.java:47)
at blueteam.Robot.run(Robot.java:48)
at blueteam.RobotPlayer.run(RobotPlayer.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at battlecode.instrumenter.SandboxedRobotPlayer.loadAndRunPlayer(SandboxedRobotPlayer.java:259)
at battlecode.instrumenter.SandboxedRobotPlayer.lambda$new$2(SandboxedRobotPlayer.java:180)
at java.lang.Thread.run(Thread.java:745)

**Comment by Formicarufa** [comment]
Method location1.directionTo(location2) returns null if the location1 is same as the location2. I'll fix that.
